#pragma once

#include <cstring>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/poll.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <arpa/inet.h>
#include <cstdlib>
#include <fstream>
#include <ctime>
#include <sstream>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <ctype.h>
#include <vector>
#include <map>
#include <cstddef>
#include <ifaddrs.h>
